# Generated by Django 3.2.11 on 2022-05-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='electro_201608',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='electro_201708',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='electro_201808',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='electro_201908',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='electro_202008',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='electro_202108',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='etcPurps',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='newPlatPlc',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='city',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='building',
            name='county',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='building',
            name='district',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='number1',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='building',
            name='number2',
            field=models.CharField(max_length=32),
        ),
    ]
