# Generated by Django 3.2.13 on 2022-04-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='email_auth',
        ),
        migrations.AddField(
            model_name='user',
            name='email_auth',
            field=models.BooleanField(default=False),
        ),
    ]
