# Generated by Django 4.0.4 on 2022-04-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='uid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='bid',
            new_name='board',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='uid',
            new_name='user',
        ),
    ]
