<<<<<<< HEAD
# Generated by Django 3.2.11 on 2022-04-29 01:30
=======
# Generated by Django 4.0.4 on 2022-04-29 06:57
>>>>>>> e0cb90863008166685e161627f4d23eae45abac2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_uid_board_user_rename_bid_comment_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='process',
            field=models.IntegerField(default=0),
        ),
    ]
