# Generated by Django 4.0.4 on 2022-04-29 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
